title: 3A Systems
locale: ru_RU
email: support@3a-systems.ru
description: >-
  Разработка, внедрение и поддержка Open Identity Platform: OpenDJ, OpenAM, OpenIG, OpenIDM 
baseurl: ""
url: "https://www.3a-systems.ru" 
keywords: openam, opendj, openidm, openig, open identity platform, identity management, access management, iam, open source, directory services, identity gateway
logo: /assets/img/logo-oip-lg.png
author:
  type: Organization
  name: ООО «ТриА Системз»
  url: https://www.3a-systems.ru
webmaster_verifications:
  google: 2StMVRK1SRD6C-jMdhCjD7r2Qotj5A4JN9Vwdq_QcAk

defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/175615630?s=200&v=4
  - scope:
      path: "fips"
    values:
      sitemap: false

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /blog/:year-:month-:day-:title
paginate_path: "/blog/page:num/"
paginate: 7

sass:
  style: compressed

highlighter: rouge
gist:
  noscript: false

markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - legal/
