title: 3A Systems
email: support@3a-systems.ru
description: >-
  Разработка, внедрение и поддержка Open Identity Platform: OpenDJ, OpenAM, OpenIG, OpenIDM 
baseurl: ""
url: "https://www.3a-systems.ru" 
keywords: openam, opendj, openidm, openig, open identity platform, identity management, access management, iam, open source, directory services, identity gateway

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

permalink: /blog/:year-:month-:day-:title
paginate_path: "/blog/page:num/"
paginate: 7

sass:
  style: compressed

highlighter: rouge
gist:
  noscript: false

markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
